name: GitHub Actions Demo Pull Request
on:
  pull_request:
    branches: [main]

jobs:

  pipeline_scan:
      runs-on: ubuntu-latest
      name: pipeline scan

      steps:         
        - name: Checkout source code to scan
          uses: actions/checkout@v3.5.3
          with:
            path: files-to-scan

        - name: Install node v16
          uses: actions/setup-node@v1
          with:
            node-version: 16
            
        - name: Scan with MetaDefender
          id: hello
          uses: vlam0120/metadefender-github-action@v34
          with:
            scan-url: 'https://api.metadefender.com/v4/file'
            scan-path: ${{ github.workspace }}/files-to-scan
            exclude-path: ${{ github.workspace }}/files-to-scan/.git
            log-file: ${{ github.workspace }}/log.txt
            apikey: ${{ secrets.MD_CLOUD_APIKEY }}
            fail-build: 1
            show-blocked-file-only: 0
            github-token: ${{ secrets.GH_TOKEN }}
        
